// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: staffer-protos/guide.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author  string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateGuideRequest) Reset() {
	*x = CreateGuideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuideRequest) ProtoMessage() {}

func (x *CreateGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuideRequest.ProtoReflect.Descriptor instead.
func (*CreateGuideRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuideRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGuideRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateGuideRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type GetGuideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGuideRequest) Reset() {
	*x = GetGuideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuideRequest) ProtoMessage() {}

func (x *GetGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuideRequest.ProtoReflect.Descriptor instead.
func (*GetGuideRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateGuideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UpdateGuideRequest) Reset() {
	*x = UpdateGuideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGuideRequest) ProtoMessage() {}

func (x *UpdateGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGuideRequest.ProtoReflect.Descriptor instead.
func (*UpdateGuideRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGuideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGuideRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateGuideRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteGuideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGuideRequest) Reset() {
	*x = DeleteGuideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGuideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGuideRequest) ProtoMessage() {}

func (x *DeleteGuideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGuideRequest.ProtoReflect.Descriptor instead.
func (*DeleteGuideRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteGuideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAllGuidesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Success bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ListAllGuidesRequest) Reset() {
	*x = ListAllGuidesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllGuidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllGuidesRequest) ProtoMessage() {}

func (x *ListAllGuidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllGuidesRequest.ProtoReflect.Descriptor instead.
func (*ListAllGuidesRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllGuidesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAllGuidesRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListAllGuidesRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchGuidesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuiedeId string `protobuf:"bytes,1,opt,name=guiede_id,json=guiedeId,proto3" json:"guiede_id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SearchGuidesRequest) Reset() {
	*x = SearchGuidesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchGuidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGuidesRequest) ProtoMessage() {}

func (x *SearchGuidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGuidesRequest.ProtoReflect.Descriptor instead.
func (*SearchGuidesRequest) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{5}
}

func (x *SearchGuidesRequest) GetGuiedeId() string {
	if x != nil {
		return x.GuiedeId
	}
	return ""
}

func (x *SearchGuidesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchGuidesRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GuideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Guide   *Guide `protobuf:"bytes,3,opt,name=guide,proto3" json:"guide,omitempty"`
}

func (x *GuideResponse) Reset() {
	*x = GuideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuideResponse) ProtoMessage() {}

func (x *GuideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuideResponse.ProtoReflect.Descriptor instead.
func (*GuideResponse) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{6}
}

func (x *GuideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GuideResponse) GetGuide() *Guide {
	if x != nil {
		return x.Guide
	}
	return nil
}

type ListAllGuidesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Guides  []*Guide `protobuf:"bytes,3,rep,name=guides,proto3" json:"guides,omitempty"`
}

func (x *ListAllGuidesResponse) Reset() {
	*x = ListAllGuidesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllGuidesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllGuidesResponse) ProtoMessage() {}

func (x *ListAllGuidesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllGuidesResponse.ProtoReflect.Descriptor instead.
func (*ListAllGuidesResponse) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllGuidesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAllGuidesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListAllGuidesResponse) GetGuides() []*Guide {
	if x != nil {
		return x.Guides
	}
	return nil
}

type Guide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author  string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *Guide) Reset() {
	*x = Guide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffer_protos_guide_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guide) ProtoMessage() {}

func (x *Guide) ProtoReflect() protoreflect.Message {
	mi := &file_staffer_protos_guide_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guide.ProtoReflect.Descriptor instead.
func (*Guide) Descriptor() ([]byte, []int) {
	return file_staffer_protos_guide_proto_rawDescGZIP(), []int{8}
}

func (x *Guide) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Guide) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Guide) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Guide) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_staffer_protos_guide_proto protoreflect.FileDescriptor

var file_staffer_protos_guide_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x1a, 0x19, 0x73, 0x74, 0x61, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x21, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x54, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x60, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x62, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x75, 0x69, 0x65, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x75, 0x69, 0x65, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x67, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x67, 0x75, 0x69, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x75,
	0x69, 0x64, 0x65, 0x52, 0x05, 0x67, 0x75, 0x69, 0x64, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x06, 0x67, 0x75, 0x69, 0x64, 0x65, 0x73, 0x22, 0x5f, 0x0a,
	0x05, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x32, 0x83,
	0x03, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x35, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x19,
	0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x75, 0x69,
	0x64, 0x65, 0x12, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x75,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12,
	0x19, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x75,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x4a,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x12,
	0x1b, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47,
	0x75, 0x69, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x75, 0x69, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staffer_protos_guide_proto_rawDescOnce sync.Once
	file_staffer_protos_guide_proto_rawDescData = file_staffer_protos_guide_proto_rawDesc
)

func file_staffer_protos_guide_proto_rawDescGZIP() []byte {
	file_staffer_protos_guide_proto_rawDescOnce.Do(func() {
		file_staffer_protos_guide_proto_rawDescData = protoimpl.X.CompressGZIP(file_staffer_protos_guide_proto_rawDescData)
	})
	return file_staffer_protos_guide_proto_rawDescData
}

var file_staffer_protos_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_staffer_protos_guide_proto_goTypes = []interface{}{
	(*CreateGuideRequest)(nil),    // 0: staff.CreateGuideRequest
	(*GetGuideRequest)(nil),       // 1: staff.GetGuideRequest
	(*UpdateGuideRequest)(nil),    // 2: staff.UpdateGuideRequest
	(*DeleteGuideRequest)(nil),    // 3: staff.DeleteGuideRequest
	(*ListAllGuidesRequest)(nil),  // 4: staff.ListAllGuidesRequest
	(*SearchGuidesRequest)(nil),   // 5: staff.SearchGuidesRequest
	(*GuideResponse)(nil),         // 6: staff.GuideResponse
	(*ListAllGuidesResponse)(nil), // 7: staff.ListAllGuidesResponse
	(*Guide)(nil),                 // 8: staff.Guide
	(*Void)(nil),                  // 9: staff.Void
}
var file_staffer_protos_guide_proto_depIdxs = []int32{
	8, // 0: staff.GuideResponse.guide:type_name -> staff.Guide
	8, // 1: staff.ListAllGuidesResponse.guides:type_name -> staff.Guide
	0, // 2: staff.GuideService.CreateGuide:input_type -> staff.CreateGuideRequest
	1, // 3: staff.GuideService.GetGuide:input_type -> staff.GetGuideRequest
	2, // 4: staff.GuideService.UpdateGuide:input_type -> staff.UpdateGuideRequest
	3, // 5: staff.GuideService.DeleteGuide:input_type -> staff.DeleteGuideRequest
	4, // 6: staff.GuideService.ListAllGuides:input_type -> staff.ListAllGuidesRequest
	5, // 7: staff.GuideService.SearchGuides:input_type -> staff.SearchGuidesRequest
	9, // 8: staff.GuideService.CreateGuide:output_type -> staff.Void
	6, // 9: staff.GuideService.GetGuide:output_type -> staff.GuideResponse
	9, // 10: staff.GuideService.UpdateGuide:output_type -> staff.Void
	9, // 11: staff.GuideService.DeleteGuide:output_type -> staff.Void
	7, // 12: staff.GuideService.ListAllGuides:output_type -> staff.ListAllGuidesResponse
	7, // 13: staff.GuideService.SearchGuides:output_type -> staff.ListAllGuidesResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_staffer_protos_guide_proto_init() }
func file_staffer_protos_guide_proto_init() {
	if File_staffer_protos_guide_proto != nil {
		return
	}
	file_staffer_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_staffer_protos_guide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGuideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGuideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGuideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGuideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllGuidesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchGuidesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllGuidesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffer_protos_guide_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staffer_protos_guide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staffer_protos_guide_proto_goTypes,
		DependencyIndexes: file_staffer_protos_guide_proto_depIdxs,
		MessageInfos:      file_staffer_protos_guide_proto_msgTypes,
	}.Build()
	File_staffer_protos_guide_proto = out.File
	file_staffer_protos_guide_proto_rawDesc = nil
	file_staffer_protos_guide_proto_goTypes = nil
	file_staffer_protos_guide_proto_depIdxs = nil
}
